async function prospectResearchTool({ linkedinUrl, companyDomain, crmAccountId }) {
  // Placeholder: in a real implementation, call LinkedIn, enrichment APIs, CRM, etc.
  return {
    summary: 'Prospect research summary would be generated here using external APIs.',
    inputs: { linkedinUrl, companyDomain, crmAccountId },
  }
}

async function emailDraftTool({ researchSummary, persona, tone }) {
  // Placeholder: in a real implementation, call your LLM with tools.
  return {
    subject: 'Cold outreach subject line from MCP server',
    body:
      'Hi {{first_name}},\n\nThis is a placeholder email draft generated by the MCP server. ' +
      'Wire this up to your LLM and tools to produce real outbound messaging.\n\nBest,\nYour SDR Agent',
    meta: { researchSummary, persona, tone },
  }
}

const EMPTY_RESEARCH = { news: [], insights: [] }

const TIMEOUT_MS = 15000

async function researchCompanyNewsTool({ companyName }) {
  const apiKey = process.env.SERPER_API_KEY
  if (!apiKey || !companyName || typeof companyName !== 'string') {
    return EMPTY_RESEARCH
  }

  const endpoint = 'https://google.serper.dev/news'

  const timeoutPromise = new Promise((_, reject) => {
    setTimeout(() => reject(new Error('Serper request timeout')), TIMEOUT_MS)
  })

  const serperPromise = (async () => {
    console.log('[research_company_news] Serper request started', { companyName })
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-API-KEY': apiKey,
      },
      body: JSON.stringify({
        q: companyName,
        num: 3,
      }),
    })

    const rawText = await response.text().catch(() => '')
    console.log('[research_company_news] Serper raw response', {
      status: response.status,
      bodyLength: rawText?.length ?? 0,
    })

    if (!response.ok) {
      throw new Error(`Serper status ${response.status}`)
    }

    const trimmed = (rawText || '').trim()
    if (!trimmed || trimmed.startsWith('<')) {
      throw new Error('Serper returned empty or HTML')
    }

    let json
    try {
      json = JSON.parse(rawText)
    } catch {
      throw new Error('Serper returned malformed JSON')
    }

    const news = Array.isArray(json.news) ? json.news : []
    const items = news.slice(0, 3).map((item) => ({
      title: item?.title ?? '',
      snippet: item?.snippet ?? '',
      source: item?.source ?? '',
      date: item?.date ?? item?.datePublished ?? null,
      url: item?.link ?? item?.url ?? '',
    }))

    console.log('[research_company_news] Serper request returned', { itemCount: items.length })
    return {
      companyName,
      news: items,
    }
  })()

  try {
    return await Promise.race([serperPromise, timeoutPromise])
  } catch (err) {
    console.log('[research_company_news] timeout or error occurred', err?.message ?? err)
    return EMPTY_RESEARCH
  }
}

const tools = {
  prospect_research: prospectResearchTool,
  email_draft: emailDraftTool,
  research_company_news: researchCompanyNewsTool,
}

module.exports = {
  tools,
}
